FROM ubuntu:latest
RUN apt-get update
RUN apt-get -y install check
RUN apt-get -y install git
RUN apt-get -y install gcc
RUN apt-get -y install g++
RUN apt-get -y install gdb
RUN apt-get -y install make